name: deploy

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install packages 📦
        run: |
          cd app
          npm clean-install
      - name: Build 🛠
        run: |
          cd app
          npx gatsby build
          ls -lh
      - name: Commit release ✒
        uses: EndBug/add-and-commit@v7
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'public'
          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Auto release commit (workflow: deploy)'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAGES_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          
